### ISSUE TITLE
Issues in 4.27

### ISSUE THREAD

**Issue by ImagineTheGames** [kvoeten/UnrealBodyPlugin#12]
I'm having issues using this with VRE built for 427...

1. Followed your steps that say exactly what to do, however they don't show where the skeletal mesh should go (I imagined inside the capsule where the mesh is, [like a normal character would], but the character is halfway thru the ground, I can see the animations working and the hands/arms ik working but i am outside the body around 50 cm's on the x and y plane offset) and the body also lags from the capsule quite significantly when moving. This is with VANILLA VRExpansion plugin.

2.  I then tried taking your .uasset and putting it into the plugin content folder and dropping it into a scene but its just filled with blueprint errors that it won't compile.

3. Could you possibly show some pics of how the proper setup is for 4.27 using this with VRE please?

**Comment by kvoeten** [comment]
As hinted at in the README I don't aim to maintain the VRExpansion sample in any form. Nor am I currently actively working on the plugin, while I do know it's compatible with Unreal 4.27, and Unreal 5.0. Your best bet is to grab an older version of VRExpansion from their repo to take a look at the setup. 

I don't know the ideal way to set it up for VRExpansian anymore, but if you don't want to go find an older VRExpansion version I do vaguely remember that the skeletal mesh you add to the Pawn (Character) has to be either absolutely positioned or detached from its parent. The body is meant to be moved manually rather than automatically move along with the pawn root transform. If the body is too far down it's also likely that the camera component isn't correct configured on the body component. 

Unfortunately I'm not currently able to help you more than that as I don't aim to update this in the foreseeable future; only at most ensuring it still works in later engine versions.

**Comment by zmifsx** [comment]
> I'm having issues using this with VRE built for 427...
> 
> 1. Followed your steps that say exactly what to do, however they don't show where the skeletal mesh should go (I imagined inside the capsule where the mesh is, [like a normal character would], but the character is halfway thru the ground, I can see the animations working and the hands/arms ik working but i am outside the body around 50 cm's on the x and y plane offset) and the body also lags from the capsule quite significantly when moving. This is with VANILLA VRExpansion plugin.
> 2. I then tried taking your .uasset and putting it into the plugin content folder and dropping it into a scene but its just filled with blueprint errors that it won't compile.
> 3. Could you possibly show some pics of how the proper setup is for 4.27 using this with VRE please?

Hey, it is actually working just fine. Make sure to enable SteamVR plugins afterward and set the grasping hand bp. That's all you need to do and it will work!

**Comment by zmifsx** [comment]
There's a downside that it won't output to VR headset and blackscreen on PIE. Need to manually add the full body stuff to new project, don't replace the vive character bp with the one supplied.

**Comment by kvoeten** [comment]
Closing the issue, it's resolved and not part of the plugin. The sample was provided for convenience and never intended to be updated.
